# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_about', models.CharField(max_length=500)),
                ('event_date', models.DateField(null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landpage.Ngo'),
        ),
    ]
